// Mocks generated by Mockito 5.3.2 from annotations
// in mechalodon_mobile/test/modules/confirm_code/confirm_code_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mechalodon_mobile/modules/reset_password/confirmation_screen/repository/confirmation_code_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ConfirmationCodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfirmationCodeRepository extends _i1.Mock
    implements _i2.ConfirmationCodeRepository {
  MockConfirmationCodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> confirmCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #confirmCode,
          [code],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> sendCode() => (super.noSuchMethod(
        Invocation.method(
          #sendCode,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
